const contractAddresses = require("../information/contractAddresses.js");

const configureReservesInput = [
  {
    name: "WBNB",
    configure: {
      asset: contractAddresses.WBNB,
      baseLTV: 7000n,
      liquidationThreshold: 7500n,
      liquidationBonus: 11000n,
      reserveFactor: 2000n,
      borrowCap: 0n,
      supplyCap: 2000000000n,
      stableBorrowingEnabled: true,
      borrowingEnabled: true,
      flashLoanEnabled: true,
    },
    setDebtCeiling: false,
    isBorrowableInIsolation: false,
    liquidationProtocolFee: 1000n,
  },
  {
    name: "WBTC",
    configure: {
      asset: contractAddresses.WBTC,
      baseLTV: 7000n,
      liquidationThreshold: 7500n,
      liquidationBonus: 11000n,
      reserveFactor: 2000n,
      borrowCap: 0n,
      supplyCap: 3000000000n,
      stableBorrowingEnabled: true,
      borrowingEnabled: true,
      flashLoanEnabled: true,
    },
    setDebtCeiling: false,
    isBorrowableInIsolation: false,
    liquidationProtocolFee: 1000n,
  },
  {
    name: "WETH",
    configure: {
      asset: contractAddresses.WETH,
      baseLTV: 8000n,
      liquidationThreshold: 8250n,
      liquidationBonus: 11000n,
      reserveFactor: 2000n,
      borrowCap: 0n,
      supplyCap: 2000000000n,
      stableBorrowingEnabled: true,
      borrowingEnabled: true,
      flashLoanEnabled: true,
    },
    setDebtCeiling: false,
    isBorrowableInIsolation: false,
    liquidationProtocolFee: 1000n,
  },
  {
    name: "LTC",
    configure: {
      asset: contractAddresses.LTC,
      baseLTV: 5000n,
      liquidationThreshold: 5500n,
      liquidationBonus: 11000n,
      reserveFactor: 2000n,
      borrowCap: 0n,
      supplyCap: 10000000n,
      stableBorrowingEnabled: true,
      borrowingEnabled: true,
      flashLoanEnabled: true,
    },
    setDebtCeiling: false,
    isBorrowableInIsolation: false,
    liquidationProtocolFee: 1000n,
  },
  {
    name: "AAVE",
    configure: {
      asset: contractAddresses.AAVE,
      baseLTV: 5000n,
      liquidationThreshold: 5500n,
      liquidationBonus: 11000n,
      reserveFactor: 2000n,
      borrowCap: 0n,
      supplyCap: 2000000n,
      stableBorrowingEnabled: true,
      borrowingEnabled: true,
      flashLoanEnabled: true,
    },
    setDebtCeiling: true,
    debtCeiling: 50000000000n,
    isBorrowableInIsolation: false,
    liquidationProtocolFee: 1000n,
  },
  {
    name: "USDT",
    configure: {
      asset: contractAddresses.USDT,
      baseLTV: 8500n,
      liquidationThreshold: 8800n,
      liquidationBonus: 11000n,
      reserveFactor: 2000n,
      borrowCap: 0n,
      supplyCap: 2000000000n,
      stableBorrowingEnabled: true,
      borrowingEnabled: true,
      flashLoanEnabled: true,
    },
    setDebtCeiling: true,
    debtCeiling: 250000000000n,
    isBorrowableInIsolation: true,
    liquidationProtocolFee: 1000n,
  },
  {
    name: "USDC",
    configure: {
      asset: contractAddresses.USDC,
      baseLTV: 8500n,
      liquidationThreshold: 8800n,
      liquidationBonus: 11000n,
      reserveFactor: 2000n,
      borrowCap: 0n,
      supplyCap: 2000000000n,
      stableBorrowingEnabled: true,
      borrowingEnabled: true,
      flashLoanEnabled: true,
    },
    setDebtCeiling: false,
    isBorrowableInIsolation: true,
    liquidationProtocolFee: 1000n,
  },
  {
    name: "BUSD",
    configure: {
      asset: contractAddresses.BUSD,
      baseLTV: 8500n,
      liquidationThreshold: 8800n,
      liquidationBonus: 11000n,
      reserveFactor: 2000n,
      borrowCap: 0n,
      supplyCap: 2000000000n,
      stableBorrowingEnabled: true,
      borrowingEnabled: true,
      flashLoanEnabled: true,
    },
    setDebtCeiling: false,
    isBorrowableInIsolation: true,
    liquidationProtocolFee: 1000n,
  },
  {
    name: "DAI",
    configure: {
      asset: contractAddresses.DAI,
      baseLTV: 8500n,
      liquidationThreshold: 8800n,
      liquidationBonus: 11000n,
      reserveFactor: 2000n,
      borrowCap: 0n,
      supplyCap: 2000000000n,
      stableBorrowingEnabled: true,
      borrowingEnabled: true,
      flashLoanEnabled: true,
    },
    setDebtCeiling: false,
    isBorrowableInIsolation: true,
    liquidationProtocolFee: 1000n,
  },
];

module.exports = configureReservesInput;
